apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: cloudacademy
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: webapp
        env:
        - name: MESSAGE
          value: "Prod CloudAcademy GitOps"